# Generated by Django 5.2 on 2025-04-24 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='sponsors',
        ),
        migrations.AddField(
            model_name='evento',
            name='sponsors_propios',
            field=models.ManyToManyField(blank=True, related_name='eventos_asociados', to='eventos.sponsor'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
