# Generated by Django 5.2 on 2025-04-24 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_remove_evento_sponsors_evento_sponsors_propios_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='sponsors_propios',
        ),
        migrations.AddField(
            model_name='evento',
            name='sponsors',
            field=models.ManyToManyField(blank=True, related_name='eventos', to='eventos.sponsor'),
        ),
    ]
